// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using bootShop.DataAccess.Data;

namespace bootShop.DataAccess.Migrations
{
    [DbContext(typeof(bootShopDbContext))]
    partial class bootShopDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("bootShop.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Telefon"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Laptop"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Tablet"
                        });
                });

            modelBuilder.Entity("bootShop.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descriptipn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Discount")
                        .HasColumnType("float");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Discount = 0.14999999999999999,
                            ImageUrl = "https://productimages.hepsiburada.net/s/65/200-200/110000007077895.jpg",
                            Name = "IPhone",
                            Price = 1500.0
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Discount = 0.14999999999999999,
                            ImageUrl = "https://productimages.hepsiburada.net/s/65/200-200/110000007077895.jpg",
                            Name = "Oppo",
                            Price = 1500.0
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Discount = 0.14999999999999999,
                            ImageUrl = "https://productimages.hepsiburada.net/s/65/200-200/110000007077895.jpg",
                            Name = "Xiaomi",
                            Price = 1500.0
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Discount = 0.14999999999999999,
                            ImageUrl = "https://productimages.hepsiburada.net/s/195/200-200/110000163717661.jpg",
                            Name = "Macbook pro",
                            Price = 1500.0
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Discount = 0.14999999999999999,
                            ImageUrl = "https://productimages.hepsiburada.net/s/195/200-200/110000163717661.jpg",
                            Name = "Dell XPS 13",
                            Price = 1500.0
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Discount = 0.14999999999999999,
                            ImageUrl = "https://productimages.hepsiburada.net/s/195/200-200/110000163717661.jpg",
                            Name = "Huawei",
                            Price = 1500.0
                        });
                });

            modelBuilder.Entity("bootShop.Entities.Product", b =>
                {
                    b.HasOne("bootShop.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("bootShop.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
